### PR TITLE
WIP: update to pybind11 2.6.0

### PR DESCRIPTION
**Pull request by henryiii**
This is a rough guess on what updating to pybind11 2.6.0 would look like. I have not used catkin (and don't really understand why normal, regular tooling can't be used...), but here's a suggestion for where to start.

### CODE REVIEW

**Comment by henryiii** [comment]
This is only meant to be a staring point, and I may have removed too much. A few points: You can customize where the CMake and include files go (see example above), and you should make sure the relative positioning is correct so that CMake can correctly discover the relative locations. You should include all of the CMake files, picking a few files out and using them in isolation is not supported.

Please continue to work on this, I just wanted to provide a starting point.

**Comment by henryiii** [comment]
For the included CMake file, I would ideally use the generated config file, but if that doesn't work, Iwould look at the Targets.CMake.in file and base your file on that.

**Comment by wxmerkt** [comment]
Hi @henryiii, 
Thanks for the PR! I am working on this locally since the changes will break downstream builds and we need to consider different workspace scenarios (devel / install). The upstream version in the ROS binaries is working (and I've commented as such in the linked issue).

What's the current / new minimum required CMake version for pybind11 in v2.6.0? I investigated upgrading back on July 31st but the new minimum required CMake version of 3.8 conflicts with some of our system requirements (to support 16.04, 18.04 and 20.04 with stock CMake) - which is why I didn't push an update yet.

Thanks,
Wolfgang

**Comment by henryiii** [comment]
3.4 on Linux, exactly so that we can support 16.04.

**Comment by wxmerkt** [comment]
I modified the PR such that it works on my machine - I think this should be good to merge. Thank you for the contribution!

**Pull request merged**
